# Generated by Django 5.1.6 on 2025-02-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='usuario',
        ),
    ]
