# Generated by Django 5.1.6 on 2025-03-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='raz_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
