# Generated by Django 5.1.6 on 2025-02-22 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_remove_contact_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_modificados', to=settings.AUTH_USER_MODEL),
        ),
    ]
