# Generated by Django 5.1.6 on 2025-02-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_contact_creado_por_contact_modificado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telefono',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
