# Generated by Django 5.1.6 on 2025-03-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_proveedor_raz_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='rut_p',
            field=models.CharField(blank=True, help_text='Formato: 00.000.000-0', max_length=12, null=True, verbose_name='Número de Rut'),
        ),
    ]
