# Generated by Django 5.1.6 on 2025-02-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_contact_pdf_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-fecha_registro']},
        ),
        migrations.AddField(
            model_name='contact',
            name='numero_registro',
            field=models.CharField(default=0, max_length=8, unique=True, verbose_name='Número de Registro'),
            preserve_default=False,
        ),
    ]
