# Generated by Django 5.1.6 on 2025-02-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_alter_contact_numero_registro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='numero_registro',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telefono',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
