# Generated by Django 5.1.6 on 2025-02-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_alter_contact_options_remove_contact_numero_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
