# Generated by Django 5.1.6 on 2025-02-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_contact_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-fecha_registro']},
        ),
        migrations.AddField(
            model_name='contact',
            name='numero_registro',
            field=models.CharField(default=0, help_text='Formato: 0000-000', max_length=8, unique=True, verbose_name='Número de Registro'),
            preserve_default=False,
        ),
    ]
