# Generated by Django 5.1.6 on 2025-02-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0018_remove_contact_rut_contact_observaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='contact',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
