# Generated by Django 5.1.6 on 2025-02-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0019_remove_contact_observaciones_contact_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='numero_registro',
            field=models.CharField(blank=True, help_text='Formato: 0000-000', max_length=8, null=True, unique=True, verbose_name='Número de Registro'),
        ),
    ]
