# Generated by Django 5.1.6 on 2025-02-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0020_alter_contact_numero_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
