# Generated by Django 5.1.6 on 2025-03-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0021_alter_contact_email_alter_contact_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
